name: â›™pr


on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  ci:
    uses: mraniki/coding_toolset/.github/workflows/ğŸ™.yml@main
    with:
      pypi_publish: true
      gitlab_mirror: true
      codeberg_mirror: true
      docker_image: false
    secrets: inherit
